spring.application.name=HospitalManager


spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true